name: Get Vault Role Token
author: mgagliardo91
branding:
  icon: lock
  color: green
description: Outputs a valid vault token for the given valut role and secret combination
inputs:
  vault-address:
    description: The vault URL
    required: true
  role-id:
    description: The vault role ID
    required: true
  secret-id:
    description: The vault role secret id
    required: true
outputs:
  vault-token:
    description: The generated vault token
    value: ${{ steps.fetch-vault-token.outputs.vault-token }}
runs:
  using: composite
  steps:
    - id: fetch-vault-token
      shell: bash
      env:
        VAULT_ADDR: ${{ inputs.vault-address }}
        ROLE_ID: ${{ inputs.role-id }}
        SECRET_ID: ${{ inputs.secret-id }}
      run: |
        VAULT_TOKEN=$(curl -s --request POST '${{ env.VAULT_ADDR }}/v1/auth/approle/login' --header 'Content-Type: application/json' --data-raw '{"role_id": "${{ env.ROLE_ID }}","secret_id": "${{ env.SECRET_ID }}"}' | jq -r '.auth.client_token')
        echo "::add-mask::$VAULT_TOKEN"
        echo "vault-token=$VAULT_TOKEN" >> $GITHUB_OUTPUT
