name: Get Current Tenants
author: melting
branding:
  icon: home
  color: orange
description: Outputs a list of tenant slugs
inputs:
  env:
    description: "Environment you are using staging | prod"
    required: false
    default: "staging"
outputs:
  tenants: 
    description: the list of tenants
    value: ${{ steps.get-tenants.outputs.tenants }}
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
    - name: Get Tenants
      id: get-tenants
      shell: bash
      run: |
        tenants=$(${{ github.action_path }}/index.js ${{ inputs.env }})
        echo "tenants=$tenants" >> $GITHUB_OUTPUT