name: Test

on:
  workflow_dispatch:

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: [nionic-runner]
    steps:
      - uses: actions/checkout@v3
      - run: |
          echo "Hello World!"
