name: Deploy

on:
  workflow_dispatch:
  push:
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'push' || (github.event.issue.pull_request != '' && contains(github.event.comment.body, '/ephemeral deploy')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config --global user.email "ephemeral@ndustrial.io"
          git config --global user.name "Ephemeral Deploy"
          git merge origin/main
          CONFLICTS=$(git ls-files -u | wc -l)
          if [ "$CONFLICTS" -gt 0 ] ; then
            echo "There is a merge conflict. Aborting"
            git merge --abort
            exit 1
          fi
      - run: |
          echo "yay"
