name: Deploy

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'ephemeral') || (github.event.issue.pull_request != '' && contains(github.event.comment.body, '/ephemeral deploy')) }}
    runs-on: ubuntu-latest
    steps:
      - uses: xt0rted/pull-request-comment-branch@v1
        if: github.event_name == 'issue_comment'
        id: comment-branch
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ steps.comment-branch.outputs.head_ref || github.head_ref || github.ref_name }}
      - name: Validate labeled
        if: github.event_name == 'issue_comment'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ $(gh pr view --json labels | jq 'any(.labels[]; .name == "bug")') = "false" ]; then
            echo -e "Ephemeral label is required in order to use `/ephemeral` command." | gh pr comment ${{github.event.number}} -F-
          fi
      - run: |
          git config --global user.email "ephemeral@ndustrial.io"
          git config --global user.name "Ephemeral Deploy"
          git merge origin/main
          CONFLICTS=$(git ls-files -u | wc -l)
          if [ "$CONFLICTS" -gt 0 ] ; then
            echo "There is a merge conflict. Aborting"
            git merge --abort
            exit 1
          fi
      - run: |
          echo "yay"
