name: Deploy

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]
  issue_comment:
    types: [created]

jobs:
  build:
    if: ${{ github.event_name == 'pull_request' || (github.event.issue.pull_request != '' && contains(github.event.comment.body, '/ephemeral deploy')) }}
    runs-on: ubuntu-latest
    steps:
      - name: Determine branch
        env:
          GITHUB_TOKEN: ${{ env.NIO_BOT_TOKEN }}
        run: |
          if [ "${{ github.event_name }}" = "issue_comment" ]; then
            echo "BRANCH=$(gh pr view ${{github.event.issue.number}} --json headRefName --jq '.headRefName')" >> $GITHUB_ENV
          elif [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "BRANCH=${{ github.head_ref || github.ref_name }}" >> $GITHUB_ENV
          fi
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.BRANCH }}
      - run: |
          git config --global user.email "ephemeral@ndustrial.io"
          git config --global user.name "Ephemeral Deploy"
          git merge origin/main
          CONFLICTS=$(git ls-files -u | wc -l)
          if [ "$CONFLICTS" -gt 0 ] ; then
            echo "There is a merge conflict. Aborting"
            git merge --abort
            exit 1
          fi
      - run: |
          echo "yay"
