name: TestE

on:
  pull_request:
    types: [opened, synchronize, labeled, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  pr:
    if: contains(github.event.pull_request.labels.*.name, 'ephemeral')
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: |
          echo $GITHUB_HEAD_REF
          echo $GITHUB_REF_NAME
          echo "${{ github.head_ref || github.ref_name }} "
          echo $GITHUB_REF
          echo ${GITHUB_REF#refs/heads/}
          echo "DEPLOYMENT_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/.*\///' | sed 's/-/_/' | awk '{print tolower($0)}')" >> $GITHUB_ENV
          echo "DEPLOYMENT_NAME=$(echo ${GITHUB_REF#refs/heads/} | sed 's/.*\///' | sed 's/-/_/' | awk '{print tolower($0)}')"
      - name: Create comment
        if: github.event_name == 'pull_request'
        run: |
          echo -e "Successfully deployed ephemeral environment to https://nsight-${{ env.DEPLOYMENT_NAME }}.dev.ndustrial.io" | gh pr comment ${{github.event.issue.number}} -F-
